INSERT INTO products (category,name,description,price_cents) VALUES
('ENTRADA','PAN AL AJO ESPECIAL','Pesto genovés...','1500'),
('ENTRADA','PAN AL AJO','Mantequilla natural...','1000'),
('PIZZA','Pizza PEPPERONI','Peperoni ahumado...','3500'),
('PIZZA','Pizza AMERICANA','Jamón de pierna...','3500'),
('PIZZA','Pizza HAWAIANA','Piña cocida...','3700'),
('PIZZA','Pizza VEGETARIANA','Aros de cebolla...','3700'),
('PIZZA','Pizza LAS 4 ESTACIONES','Jamón, champiñones...','3800'),
('PIZZA','Pizza HUACHANA','Salchicha huachana...','3800'),
('PIZZA','Pizza MARGHERITA','Albahaca fresca...','3500'),
('PIZZA','Pizza LA CHARAPITA','Cecina, chorizo...','4100'),
('PIZZA','Pizza LA ARGENTINA','Chorizo finas hierbas...','4100'),
('PIZZA','Pizza LA NAPOLITANA','Pesto, tomates cherry...','3800'),
('PIZZA','Pizza LA ESPAÑOLA','Chorizo español...','4000'),
('BEBIDA','AGUA SAN MATEO SIN GAS','',400),
('BEBIDA','INKA COLA ZERO 500 ML','',500),
('BEBIDA','COCA COLA ZERO 500 ML','',500),
('BEBIDA','AGUA SAN MATEO CON GAS','',400),
('BEBIDA','COCA COLA ORIGINAL 500 ML','',500),
('BEBIDA','INKA COLA ORIGINAL 500 ML','',500);